name: ci

on:
  push:
    branches:
      - 'build'

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.actor }}/${{ github.repository }}:latest 
# jobs:
#   build-and-publish-latest:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master' # Running this job only for master branch

#     steps:
#         - uses: actions/checkout@v2 # Checking out the repo

#         - name: Build and Publish latest Docker image
#           uses: VaultVulp/gp-docker-action@1.1.12
#           with:
#               github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
#               image-name: my-cool-service # Provide only Docker image name, tag will be automatically set to latest
#               dockerfile: Dockerfile_server